language: cpp

dist: bionic

compiler:
  - gcc

before_install:
  - sudo apt-get install -y freeglut3-dev libglfw3-dev

install:
  - ./configure

before_script:
  # create a build folder for the out-of-source build
  - mkdir build
  # switch to build directory
  - cd build
  # run cmake;
  - cmake ..

script:
  # once CMake has done its job we just build using make as usual
  - make
  # if the project uses ctest we can run the tests like this
  - make test
