language: cpp

dist: bionic 

compiler:
  - gcc

cache: ccache

addons:
  sonarcloud:
    organization: "mescourrou-github"
    token:
      secure: "c39f8a2b2207d2e93664cd6c07d51c988d41f653"
  apt:
    update: true
  git:
    depth: false

before_install:
  - sudo apt-get install -y freeglut3-dev libglfw3-dev
  - sudo apt-get install -y libudev-dev
  - sudo apt-get install -y libopenal-dev libalut-dev 
  - sudo apt-get install -y libflac++-dev libvorbis-dev 
  - sudo apt-get install -y libxrandr-dev

install:
  - ./configure

before_script:
  # create a build folder for the out-of-source build
  - mkdir build
  # switch to build directory
  - cd build
  # run cmake;
  - cmake ..

script:
  - make clean
  - build-wrapper-linux-x86-64 --out-dir bw-output make all
  - make test
  - sonar-scanner
